---
name: synchronize repo test

"on":
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  provide_repos_json:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout the saurus repo (B)
        uses: actions/checkout@v3

      - name: Set Matrix
        id: set-matrix
        run: |
          REPOS=$(echo $(cat ././repos.json) | sed 's/ //g' )
          echo "::set-output name=matrix::$REPOS"
          echo $REPOS
  
  sync_repos:
    needs: provide_repos_json
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        repos: ${{ fromJson(needs.provide_repos_json.outputs.matrix) }}
    steps: 
      - name: set repos
        run: |
          echo ${{matrix.repos.name}}
          printf $(pwd)

      - name: Checkout the saurus repo (B)
        uses: actions/checkout@v3
  
      - name: Clone repo A which is about to be synchronized
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: maxwolfs/${{matrix.repos.name}}
          path: 'repo_to_be_edited'

      - name: remove git folders from A
        run: |
          rm -rf $(pwd)/repo_to_be_edited/.git
          printf $(pwd)

      - name: remove README.md files from A
        run: |
          find $(pwd)/repo_to_be_edited -name "README.md" | xargs rm -f
          printf $(pwd)

      - name: create saurus subdirectory
        run: |
          mkdir $(pwd)/docs/${{matrix.repos.name}} || true
          printf $(pwd)

      - name: copy docs content from A to B
        run: |
          cp -r $(pwd)/repo_to_be_edited/docs/* $(pwd)/docs/${{matrix.repos.name}}  
          
      - name: remove repo A
        run: |
          rm -rf $(pwd)/repo_to_be_edited/

      - name: commit and push B
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'bot@maxwolfs'
          committer_name: Action Bot
          commit: --signoff
          message: "distillate"
          push: true
          add: "docs"






    # yaml example
    #     provide_repos_list:
    # runs-on: ubuntu-latest
    # outputs:
    #   matrix: ${{ steps.yaml-data.outputs.data }}
    # steps:
    #   - name: Checkout the saurus repo (B)
    #     uses: actions/checkout@v3

    #   - name: Run read-yaml action
    #     id: yaml-data
    #     uses: jbutcher5/read-yaml@main      
    #     with:
    #       file: './repos.yml'          
    #       key-path: '["repos"]'

    #   - name: Set Matrix
    #     run: echo "${{ steps.yaml-data.outputs.data }}"