---
name: synchronize repo test

"on":
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  provide_repos_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the saurus repo (B)
        uses: actions/checkout@v3

      - name: Set Matrix
        run: |
          REPOS=$(echo $(cat ././repos.json) | sed 's/ //g' )
          echo "::set-output name=matrix::$REPOS"
          echo $REPOS

    outputs:
      matrix: $REPOS

  sync_repos:
    needs: provide_repos_json
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        repos: ${{fromJson(needs.provide_repos_json.outputs.matrix)}}
    steps: 
      - name: set repos
        run: |
          REPOS=${{fromJson(needs.provide_repos_json.outputs.matrix)}}
          echo $REPOS

      - name: Checkout the saurus repo (B)
        uses: actions/checkout@v3
  
      # - name: Clone repo A which is about to be synchronized
      #   uses: sudosubin/git-clone-action@v1.0.1
      #   with:
      #     repository: 'SovereignCloudStack/Docs'
      #     path: 'repo_to_be_edited'

      # - name: remove git folders from A
      #   run: |
      #     rm -rf $(pwd)/repo_to_be_edited/.git

      # - name: remove README.md files from A
      #   run: |
      #     find $(pwd)/repo_to_be_edited -name "README.md" | xargs rm -f

      # - name: create saurus subdirectory
      #   run: |
      #     mkdir $(pwd)/docs/testbed || true

      # - name: copy docs content from A to B
      #   run: |
      #     cp -r $(pwd)/repo_to_be_edited/docs/* $(pwd)/docs/testbed
          
      # - name: remove repo A
      #   run: |
      #     rm -rf $(pwd)/repo_to_be_edited/

      # - name: commit and push B
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     author_name: 'bot@SovereignCloudStack'
      #     committer_name: SovereignCloudStack Bot
      #     commit: --signoff
      #     message: "distillate"
      #     push: true
      #     add: "docs"