---
name: synchronize repo test

"on":
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  get-repos-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the saurus repo (B)
        uses: actions/checkout@v3

      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main      
        with:
          file: './repos.yml'          
          key-path: '["repos"]'

      - name: Set Matrix
        run: echo "${{ matrix.repos }}"

    outputs:
      matrix: ${{ steps.yaml-data.outputs.data.repos }}

  sync-repos:
    needs: get-repos-list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repos: ${{ fromJson(needs.get-repos-json.outputs.matrix) }}
    steps: 
      - name: echo repos
        run: echo "${{ matrix.repos }}"

      - name: Checkout the saurus repo (B)
        uses: actions/checkout@v3
  
      # - name: Clone repo A which is about to be synchronized
      #   uses: sudosubin/git-clone-action@v1.0.1
      #   with:
      #     repository: 'SovereignCloudStack/Docs'
      #     path: 'repo_to_be_edited'

      # - name: remove git folders from A
      #   run: |
      #     rm -rf $(pwd)/repo_to_be_edited/.git

      # - name: remove README.md files from A
      #   run: |
      #     find $(pwd)/repo_to_be_edited -name "README.md" | xargs rm -f

      # - name: create saurus subdirectory
      #   run: |
      #     mkdir $(pwd)/docs/testbed || true

      # - name: copy docs content from A to B
      #   run: |
      #     cp -r $(pwd)/repo_to_be_edited/docs/* $(pwd)/docs/testbed
          
      # - name: remove repo A
      #   run: |
      #     rm -rf $(pwd)/repo_to_be_edited/

      # - name: commit and push B
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     author_name: 'bot@SovereignCloudStack'
      #     committer_name: SovereignCloudStack Bot
      #     commit: --signoff
      #     message: "distillate"
      #     push: true
      #     add: "docs"