---
name: json test

"on":
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout the saurus repo (B)
      uses: actions/checkout@v3

    - id: set-matrix
      run: |
        JSON=$(cat ././repos.json | sed 's/ //g')
        printf "::set-output name=matrix::${JSON//'%'/'%25'}"
        printf "${{ steps.set-matrix.outputs.matrix }}"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: build