  provide_repos_list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.yaml-data.outputs.data }}
    steps:
      - name: Checkout the saurus repo (B)
        uses: actions/checkout@v3

      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main      
        with:
          file: './repos.yml'          
          key-path: '["repos"]'

      - name: Set Matrix
        run: echo "${{ steps.yaml-data.outputs.data }}"